import type { Metadata } from "next";
import "./globals.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "2024 TL Bootcamp - James",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
